import type { Metadata } from 'next';
import localFont from 'next/font/local';

import AuthProvider from '@/provider/AuthProvider';
import PostProvider from '@/provider/PostProvider';
import { COLORS } from '@/styles';

import './globals.css';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'luna-code',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="jp">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        style={{ backgroundColor: COLORS.BLACK, position: 'relative' }}
      >
        <AuthProvider>
          <PostProvider>{children}</PostProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
